name: jester
version: 0.0.1
author: Vizidrix <admin@vizidrix.com>
description: An actor framework for Dart
homepage: https://github.com/Vizidrix/jester
documentation: https://github.com/Vizidrix/jester/tree/master/doc
dev_dependencies:
  unittest: '>=0.4.7'
